port: CHANGE_ME
db:
  drv: pgx
  host: localhost
  port: 5432
  name: rea
  user: rea
  password: CHANGE_ME
  ssl_enabled: false

cors:
  allow_origins:
    - http://localhost:8080

front_end:
  base_url: http://localhost:8080
  url_prefixes_to_match: 
    - http://localhost:8080/
    - localhost:8080/