db:
  drv: pgx
  host: ec2-52-23-45-36.compute-1.amazonaws.com
  port: 5432
  name: d9fsuo4nbdlatl
  user: hcccldpmhqzstc
  password: CHANGE_ME
  ssl_enabled: true

cors:
  allow_origins:
    - https://polar-mountain-99143.herokuapp.com

front_end:
  base_url: https://polar-mountain-99143.herokuapp.com
  url_prefixes_to_match: 
    - https://polar-mountain-99143.herokuapp.com/
    - polar-mountain-99143.herokuapp.com/